// create a list of 40 company names, positions, durations, locations, and descriptions with internship links in different levels of the src/component/response/data.ts file.

import { JobCardProps } from '../layouts/job-card';

const data: JobCardProps[] = [
  {
    company: 'Google',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'Mountain View, CA',
    description: "Work on Google's core products and see how they are built.",
    link: 'https://www.google.com',
  },
  {
    company: 'Facebook',
    position: 'Product Manager Intern',
    duration: '4 months',
    location: 'Menlo Park, CA',
    description: "Work on Facebook's core products and see how they are built.",
    link: 'https://www.facebook.com',
  },
  {
    company: 'Amazon',
    position: 'Data Scientist Intern',
    duration: '3 months',
    location: 'Seattle, WA',
    description: "Work on Amazon's core products and see how they are built.",
    link: 'https://www.amazon.com',
  },
  {
    company: 'Microsoft',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'Redmond, WA',
    description:
      "Work on Microsoft's core products and see how they are built.",
    link: 'https://www.microsoft.com',
  },
  {
    company: 'Apple',
    position: 'Product Manager Intern',
    duration: '4 months',
    location: 'Cupertino, CA',
    description: "Work on Apple's core products and see how they are built.",
    link: 'https://www.apple.com',
  },
  {
    company: 'Tesla',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'Palo Alto, CA',
    description: "Work on Tesla's core products and see how they are built.",
    link: 'https://www.tesla.com',
  },
  {
    company: 'Netflix',
    position: 'Product Manager Intern',
    duration: '4 months',
    location: 'Los Gatos, CA',
    description: "Work on Netflix's core products and see how they are built.",
    link: 'https://www.netflix.com',
  },
  {
    company: 'Uber',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'San Francisco, CA',
    description: "Work on Uber's core products and see how they are built.",
    link: 'https://www.uber.com',
  },
  {
    company: 'Airbnb',
    position: 'Product Manager Intern',
    duration: '4 months',
    location: 'San Francisco, CA',
    description: "Work on Airbnb's core products and see how they are built.",
    link: 'https://www.airbnb.com',
  },
  {
    company: 'Lyft',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'San Francisco, CA',
    description: "Work on Lyft's core products and see how they are built.",
    link: 'https://www.lyft.com',
  },
  {
    company: 'Pinterest',
    position: 'Product Manager Intern',
    duration: '4 months',
    location: 'San Francisco, CA',
    description:
      "Work on Pinterest's core products and see how they are built.",
    link: 'https://www.pinterest.com',
  },
  {
    company: 'Slack',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'San Francisco, CA',
    description: "Work on Slack's core products and see how they are built.",
    link: 'https://www.slack.com',
  },
  {
    company: 'Zoom',
    position: 'Product Manager Intern',
    duration: '4 months',
    location: 'San Jose, CA',
    description: "Work on Zoom's core products and see how they are built.",
    link: 'https://www.zoom.com',
  },
  {
    company: 'Salesforce',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'San Francisco, CA',
    description:
      "Work on Salesforce's core products and see how they are built.",
    link: 'https://www.salesforce.com',
  },
  {
    company: 'Oracle',
    position: 'Product Manager Intern',
    duration: '4 months',
    location: 'Redwood City, CA',
    description: "Work on Oracle's core products and see how they are built.",
    link: 'https://www.oracle.com',
  },
  {
    company: 'IBM',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'Armonk, NY',
    description: "Work on IBM's core products and see how they are built.",
    link: 'https://www.ibm.com',
  },
  {
    company: 'HP',
    position: 'Product Manager Intern',
    duration: '4 months',
    location: 'Palo Alto, CA',
    description: "Work on HP's core products and see how they are built.",
    link: 'https://www.hp.com',
  },
  {
    company: 'Dell',
    position: 'Software Engineer Intern',
    duration: '3 months',
    location: 'Round Rock, TX',
    description: "Work on Dell's core products and see how they are built.",
    link: 'https://www.dell.com',
  },
];

export default data;
